apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
items:

- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    labels:
      build: knowage
      app: knowage
    name: knowage
  spec:
    lookupPolicy:
      local: true

- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    labels:
      build: knowage
      app: knowage
    name: knowage
  spec:
    resources:
      limits:
        cpu: '1'
        memory: 3192Mi
      requests:
        cpu: 50m
        memory: 512Mi
    failedBuildsHistoryLimit: 1
    output:
      to:
        kind: ImageStreamTag
        name: 'knowage:8.0.0'
    runPolicy: Serial
    source:
      contextDir: '/dockerfiles'
      git:
        ref: master
        uri: https://github.com/spotet/knowage.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: 'tomcat-webserver:9-jdk8'
          namespace: openshift
      type: Docker
    successfulBuildsHistoryLimit: 1
    triggers:
      - type: ConfigChange