apiVersion: template.openshift.io/v1
kind: Template
message: |-
  Below the information of generated entries, tokens and passwords :

    PROJECT_NAME          : ${PROJECT_NAME}

metadata:
  annotations:
    description: |
      This template deploys Knowage application.
    openshift.io/display-name: Claims Knowage
    iconClass: "icon-openshift"
    template.openshift.io/documentation-url: https://www.sigma.fr
    tags: claims,knowage
  name: knowage-claims

parameters:
- description: Target Project Name
  displayname: Target Project Name
  name: PROJECT_NAME
  required: true
- description: Username for MariaDB user that will be used for accessing the database.
  displayName: MariaDB Connection Username
  from: user[A-Z0-9]{3}
  generate: expression
  name: MARIADB_USER
  required: true

objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: knowage
    name: knowage
  spec:
    replicas: 1
    revisionHistoryLimit: 3
    selector:
      app: knowage
      deploymentconfig: knowage
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: knowage
          deploymentconfig: knowage
      spec:
        containers:
        - env:
          - name: DB_ENV_MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: mariadb
          - name: DB_ENV_MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: mariadb
          - name: DB_ENV_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: mariadb
          - name: DB_PORT_3306_TCP_ADDR
            value: mariadb
          - name: DB_PORT_3306_TCP_PORT
            value: "3306"
          - name: HMAC_KEY
            value: abc123
          - name: PASSWORD_ENCRYPTION_SECRET
            value: def456
          - name: DB_DB
            valueFrom:
              secretKeyRef:
                key: database-name
                name: mariadb
          - name: DB_PORT
            value: "3306"
          - name: DB_HOST
            value: mariadb
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: mariadb
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                key: database-password
                name: mariadb
          - name: CACHE_DB_DB
            valueFrom:
              secretKeyRef:
                key: database-name
                name: mariadb
          - name: CACHE_DB_PORT
            value: "3306"
          - name: CACHE_DB_HOST
            value: mariadb
          - name: CACHE_DB_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: mariadb
          - name: CACHE_DB_PASS
            valueFrom:
              secretKeyRef:
                key: database-password
                name: mariadb
          - name: PUBLIC_ADDRESS
            value: 127.0.0.1
          image: docker-registry.default.svc:5000/spo-dev/knowage@sha256:734318334404fb80b6878c275cc7e519f35810b4d9abe7d566cbdc850c10b2e5
          imagePullPolicy: Always
          name: knowage
          ports:
          - containerPort: 8009
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - knowage
        from:
          kind: ImageStreamTag
          name: knowage:latest
          namespace: spo-dev
        lastTriggeredImage: docker-registry.default.svc:5000/spo-dev/knowage@sha256:734318334404fb80b6878c275cc7e519f35810b4d9abe7d566cbdc850c10b2e5
      type: ImageChange

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: knowage
    name: knowage
  spec:
    ports:
    - name: 8009-tcp
      port: 8009
      protocol: TCP
      targetPort: 8009
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: knowage
    sessionAffinity: None
    type: ClusterIP

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: knowage
    name: knowage
  spec:
    host: knowage-spo-dev.paas-rec.sigma.fr
    port:
      targetPort: 8080
    tls:
      termination: edge
    to:
      kind: Service
      name: knowage
      weight: 100
    wildcardPolicy: None